data:
  train:
    enable-caching: true
    cache-dir-path: ./cache
    path: ./datasets/drugsComTrain_raw.csv
    sampling:
      number: 5100
      seed: 42
dtm:
  min-df-threshold: 0.005
lda:
  enable-traning: true
  models-dir-path: ./models
  topics: 3
  iterations: 3
  alpha: 0.1
  beta: 0.01
  seed: 42
result:
  results-dir-path: ./results
  top-words: 10
